import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";
import NavbarComponents from "./components/layout/navbar";
import { Providers } from "./nextuiProvider";
import Sidebar from "./components/layout/sidebar";
import NavBar_ from "./components/layout/_navbar";

export const metadata: Metadata = {
  title: "Webfood",
  description: "Generated by create next app",
};

const inter = Lora({
  subsets: ["math", "cyrillic", "latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body
        className={` scroll-smooth antialiased min-h-screen w-full max-w-full text-black overflow-auto`}>
        <Providers>
          <NavBar_ />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
